export const sliderImages = [
    "http://www.planwallpaper.com/static/images/bicycle-1280x720.jpg",
    "http://www.planwallpaper.com/static/images/HD-Wallpapers1_FOSmVKg.jpeg",
    "http://www.intrawallpaper.com/static/images/HD-Wallpapers-C76.jpg",
    "http://www.bhmpics.com/thumbs/dambo_the_bottle_funny_situation-t3.jpg",
    "https://www.hdwallpapers.net/previews/hot-air-balloon-over-the-mountain-987.jpg",
    "https://www.hdwallpapers.net/previews/rain-on-the-window-1076.jpg",
    "https://www.hdwallpapers.net/previews/rain-on-the-window-1076.jpg",
    "https://i.ytimg.com/vi/xLOrfcqQS1Y/maxresdefault.jpg",
    "http://www.planwallpaper.com/static/images/abstraction_light_neon_glitter_97687_1920x1080.jpg",
    "http://coolwallpaperz.info/user-content/uploads/wall/o/20/boat-desert-sailing-hd-jootix-223115.jpg",
    "http://coolwallpaperz.info/user-content/uploads/wall/o/20/boat-desert-sailing-hd-jootix-223115.jpg",
    "https://www.qdtricks.net/wp-content/uploads/2016/05/wallpaper-hd-download.jpg",
    "http://www.planwallpaper.com/static/images/6813800-toy-car-wallpaper-hd.jpg",
]